# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'service.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(609, 415)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("background-color: rgb(33, 33, 33)")
        self.twStaffs = QtWidgets.QTableWidget(Form)
        self.twStaffs.setGeometry(QtCore.QRect(15, 190, 571, 192))
        self.twStaffs.setStyleSheet("color: rgb(20, 255, 236)")
        self.twStaffs.setObjectName("twStaffs")
        self.twStaffs.setColumnCount(0)
        self.twStaffs.setRowCount(0)
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(430, 50, 75, 46))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.pushButton = QtWidgets.QPushButton(self.splitter)
        self.pushButton.setStyleSheet("color: rgb(20, 255, 236)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.splitter)
        self.pushButton_2.setStyleSheet("color: rgb(20, 255, 236)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 311, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("color: rgb(20, 255, 236)")
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("color: rgb(20, 255, 236)")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("color: rgb(20, 255, 236)")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setStyleSheet("color: rgb(20, 255, 236)")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.leID = QtWidgets.QLineEdit(self.layoutWidget)
        self.leID.setStyleSheet("color: rgb(20, 255, 236)")
        self.leID.setObjectName("leID")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.leID)
        self.lename = QtWidgets.QLineEdit(self.layoutWidget)
        self.lename.setStyleSheet("color: rgb(20, 255, 236)")
        self.lename.setObjectName("lename")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lename)
        self.lecode = QtWidgets.QLineEdit(self.layoutWidget)
        self.lecode.setStyleSheet("color: rgb(20, 255, 236)")
        self.lecode.setObjectName("lecode")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lecode)
        self.lecount = QtWidgets.QLineEdit(self.layoutWidget)
        self.lecount.setStyleSheet("color: rgb(20, 255, 236)")
        self.lecount.setObjectName("lecount")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lecount)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Open"))
        self.pushButton_2.setText(_translate("Form", "Insert"))
        self.label.setText(_translate("Form", "ID"))
        self.label_2.setText(_translate("Form", "name"))
        self.label_3.setText(_translate("Form", "code"))
        self.label_4.setText(_translate("Form", "count"))
